[tool.poetry]
name = "switch-screenshot-downloader"
version = "0.1.0"
description = ""
authors = ["Carlos Chacón <chaconmooncarlos@gmail.com>"]
readme = "README.md"

packages = [
    {include = "bluesky_API", from = "switch_screenshot_downloader"},
    {include = "switch_utilities", from = "switch_screenshot_downloader"},
]
[tool.poetry.dependencies]
python = "3.12.5"
pywifi = "^1.1.12"
comtypes = "^1.4.9"
requests = "^2.32.3"
selenium = "^4.28.1"
atproto = "^0.0.58"
python-dotenv = "^1.0.1"
ruff = "^0.9.4"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
